version: "3"
services:

#---k_114wbs_dev-+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+----#
  114wbs_dev:
    container_name: 114wbs_dev
    build: ../k_914set_dev/114set_dev
    volumes:
      # - ./:/usr/src/app # ↓.yml統合に伴う修正（.jsonを参照させる）
      - ../k_114wbs_dev:/usr/src/app
    # working_dir: /usr/src/app/k_114wbs_dev
    working_dir: /usr/src/app
    environment:
      - CHOKIDAR_USEPOLLING=true # Hotreload
    ports:
      - "3000:3000"
    # command: sh -c "./114set_dev/npmset.sh && yarn start" # ShellScript for boot && ShellScript for initialize.
    command: sh -c "npm install && yarn start"
    tty: true
    stdin_open: true
    networks:
      - myportfolio_k_dev_network

#---k_214api_dev-+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+----#
  214api_dev:
    container_name: 214api_dev
    # build:
      # context: ../k_214api_dev/src
      # dockerfile: ../../k_914set_dev/214set_dev/Dockerfile
    build: ./214set_dev
    tty: true
    volumes:
      - ../k_214api_dev/src:/go/src
    ports:
      - "8080:8080"
      # ホストのポート番号（重複不可）：コンテナのポート番号（重複可）
    networks:
      - myportfolio_k_dev_network
    depends_on:
      - 314dbs_dev

#---k_314dbs_dev-+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+----#
  314dbs_dev:
    # image: postgres:14
    container_name: 314dbs_dev
    build: ./314set_dev
    command: -c 'config_file=/etc/postgresql/postgresql.conf'
    ports:
      - 5432:5432
    volumes:
      - db-store:/var/lib/postgresql/data
      - ../k_314dbs_dev/initdb:/docker-entrypoint-initdb.d
      - ../k_314dbs_dev/config/postgresql.conf:/etc/postgresql/postgresql.conf
    environment:
        POSTGRES_PASSWORD: ${PGSQL_PW}
    networks:
      - myportfolio_k_dev_network

#---k_314dbs_dev-+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+----#
volumes:
  db-store:

#---k_214aps_dev-+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+----#
networks:
  myportfolio_k_dev_network:
    driver: bridge

#---note---+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+----#
# db-storeが生成されるような行為を行うときには「.sql」ファイルを
# 格納していないと初期化処理がスキップされるので注意！

# Dockerfile：コンテナ自体の初期設定のみ(動作に必要なツールのインストールと設定変更)記載
# docker-compose.yml：環境依存情報のみ(ポートとかストレージとか、プログラムの起動コマンドとか)記載
