// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0

package build_sqlc

import (
	"database/sql"
	"time"
)

type AccountAttribute struct {
	AccountID        int32          `json:"account_id"`
	SelfIntroduction sql.NullString `json:"self_introduction"`
	TwitterUrl       sql.NullString `json:"twitter_url"`
	FacebookUrl      sql.NullString `json:"facebook_url"`
	InstagramUrl     sql.NullString `json:"instagram_url"`
	YoutubeChannel   sql.NullString `json:"youtube_channel"`
	UpdateDate       time.Time      `json:"update_date"`
	UpdateID         string         `json:"update_id"`
	PicID01          string         `json:"pic_id_01"`
	PicID02          sql.NullString `json:"pic_id_02"`
	PicID03          sql.NullString `json:"pic_id_03"`
	Skill            string         `json:"skill"`
}

type AccountMaster struct {
	UserID           int32          `json:"user_id"`
	AccountName      string         `json:"account_name"`
	MailAddless      string         `json:"mail_addless"`
	Password         string         `json:"password"`
	ZipCode          string         `json:"zip_code"`
	BarthDate        time.Time      `json:"barth_date"`
	TimeZone         string         `json:"time_zone"`
	Language         string         `json:"language"`
	Status           string         `json:"status"`
	RegistrationDate time.Time      `json:"registration_date"`
	Rate             sql.NullString `json:"rate"`
}
