FROM node:16.15.0-alpine
WORKDIR /usr/src/app

# RUN npm install -g create-react-app
# RUN create-react-app . --typescript

COPY strset.sh /usr/local/bin
CMD ["sh", "../../../usr/local/bin/strset.sh"]
