version: '3'

services:
  db:
    image: postgres:14
    container_name: 311dbs_dev # 変更：postgres -> 311dbs_dev
    command: -c 'config_file=/etc/postgresql/postgresql.conf' # 追加
    ports:
      - 5432:5432
    volumes: # 永続データはどこにおいてどう記述する？
      - db-store:/var/lib/postgresql/data
      - ./script:/docker-entrypoint-initdb.d
      - ./config/postgresql.conf:/etc/postgresql/postgresql.conf # 追加
    environment:
      - POSTGRES_PASSWORD=passw0rd
volumes:
  db-store: