version: "3"
services:

# #---110wbs_tst---+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+----#
#   110wbs_tst:
#     container_name: 110wbs_tst
#     build: ./110wbs_tst
#     volumes:
#       - ../k_01_src/110wbs_src:/usr/src/app
#       - wbs-vol:/usr/src/app
#     # working_dir: /usr/src/app/110wbs_tst
#     working_dir: /usr/src/app
#     environment:
#       - CHOKIDAR_USEPOLLING=true # Hotreload
#     ports:
#       - "3000:3000"
#     tty: true
#     stdin_open: true
#     networks:
#       - STGprd_devpkg_tst_network
#     # platform: linux/x86_64

# #---124api_tst---+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+----#
#   124api_tst:
#     container_name: 124api_tst
#     # build:
#     #   context: ../k_01_src/124api_src/src
#     #   dockerfile: ../../../k_03_tst/124api_tst/Dockerfile
#     build: ./124api_tst
#     tty: true
#     volumes:
#       # - ../k_01_src/124api_src/src:/go/src # Activate for ShellScript Operation.
#       - api-vol:/go/src # Activate for Dockerfile Opration.
#     ports:
#       - "8080:8080"
#       # Port No of Host(non-overlapable):Port No of Container(overlappable)
#     networks:
#       - STGprd_devpkg_tst_network
#     depends_on:
#       - 130dbs_tst

#---130dbs_tst---+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+----#
  130dbs_tst:
    container_name: 130dbs_tst
    # image: postgres:14
    build: ./130dbs_tst
    command: -c 'config_file=/etc/postgresql/postgresql.conf'
    ports:
      - 5678:5432
    volumes:
      - dbs-vol:/var/lib/postgresql/data
    environment:
        POSTGRES_PASSWORD: ${PGSQL_PW}
    # networks:
    #   - STGprd_devpkg_tst_network

#---130dbs_tst---+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+----#
volumes:
  # wbs-vol:
  # api-vol:
  dbs-vol:

#---k_214aps_tst-+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+----#
# networks:
#   STGprd_devpkg_dev_network:
#     driver: bridge

#---note---+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+----#
# db-storeが生成されるような行為を行うときには「.sql」ファイルを
# 格納していないと初期化処理がスキップされるので注意！

# Dockerfile：コンテナ自体の初期設定のみ(動作に必要なツールのインストールと設定変更)記載
# docker-compose.yml：環境依存情報のみ(ポートとかストレージとか、プログラムの起動コマンドとか)記載
