version: "3"
services:

# #---110wbs_tst---+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+----#
#   110wbs_tst:
#     container_name: 110wbs_tst
#     build: ./110wbs_tst
#     volumes:
#       - ../k_01_src/110wbs_src:/usr/src/app
#       - wbs-vol:/usr/src/app
#     # working_dir: /usr/src/app/110wbs_tst
#     working_dir: /usr/src/app
#     environment:
#       - CHOKIDAR_USEPOLLING=true # Hotreload
#     ports:
#       - "3000:3000"
#     tty: true
#     stdin_open: true
#     networks:
#       - STGprd_devpkg_tst_network
#     # platform: linux/x86_64

#---120api_tst---+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+----#
  120api_tst:
    container_name: 120api_tst
    build: ./120api_tst
    tty: true
    volumes:
      # - ../k_01_src/124api_src/src:/go/src # Activate for ShellScript Operation.
      - api-vol:/go/src # Activate for Dockerfile Opration.
    ports:
      - "8081:8080"
      # Port No of Host(non-overlapable):Port No of Container(overlappable)
    # networks:
    #   - STGprd_devpkg_tst_network
    # depends_on:
    #   - 130dbs_tst

# #---130dbs_tst---+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+----#
#   130dbs_tst:
#     container_name: 130dbs_tst
#     # image: postgres:14
#     build: ./130dbs_tst
#     # working_dir: /usr/src/dbstore
#     ports:
#       - 5433:5432
#     volumes:
#       - dbs-vol:/var/lib/postgresql/data
#       - ../k_03_tst/130dbs_tst/:/usr/src/dbstore
#     environment:
#         POSTGRES_PASSWORD: ${PGSQL_PW}
#     command: sh -c `pg_restore.sh 130dbs_tst`
#     # networks:
#     #   - STGprd_devpkg_tst_network

#---130dbs_tst---+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+----#
volumes:
  # wbs-vol:
  # api-vol:
  dbs-vol:

#---k_214aps_tst-+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+----#
# networks:
#   STGprd_devpkg_dev_network:
#     driver: bridge

#---note---+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+----#
# db-storeが生成されるような行為を行うときには「.sql」ファイルを
# 格納していないと初期化処理がスキップされるので注意！

# Dockerfile：コンテナ自体の初期設定のみ(動作に必要なツールのインストールと設定変更)記載
# docker-compose.yml：環境依存情報のみ(ポートとかストレージとか、プログラムの起動コマンドとか)記載
