version: "3"
services:
  node:    # コンテナ名
    build: .
    volumes:
      - ./:/usr/src/app
    ports:
      - "3000:3000"
    command: sh -c "cd k_101_re_wbs_d && yarn start"
    # 末尾の「_d」はdocker側で作成されるため識別用に付加。（git cloneで作成された場合は「_g」を付加。）
    stdin_open: true


# 今後の課題：コンテナ名を指定すること。
