version: "3"
services:

#---k_211aps_dev-+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+----#
  211aps_dev:
    build: ../k_901set_dev/211set_dev
    tty: true
    volumes:
      - ../k_211aps_dev:/go/src/work
    networks:
      - postgres-test-network

#---k_310dbs_dev-+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+----#
  310dbs_dev:
    image: postgres:14
    command: -c 'config_file=/etc/postgresql/postgresql.conf' # 追加
    ports:
      - 5432:5432
    volumes:
      - db-store:/var/lib/postgresql/data
      - ./310set_dev/initdb:/docker-entrypoint-initdb.d
      - ./310set_dev/config/postgresql.conf:/etc/postgresql/postgresql.conf
    environment:
      - POSTGRES_PASSWORD=${PGSQL_PW}
    networks:
      - postgres-test-network

#---k_310dbs_dev-+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+----#
volumes:
  db-store:

##---k_211aps_dev-+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+----#
networks:
  postgres-test-network:
    driver: bridge
