version: "3"
services:

#---k_111wbs_dev-+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+----#
  112wbs_dev:
    build: ../k_902set_dev/112set_dev
    volumes:
    # - ./:/usr/src/app # ↓.yml統合に伴う修正（.jsonを参照させる）
      - ../k_112wbs_dev:/usr/src/app
  # working_dir: /usr/src/app/k_111wbs_dev     # バインドマウント
    working_dir: /usr/src/app
    environment:
      - CHOKIDAR_USEPOLLING=true               # ホットリロード
    ports:
      - "3000:3000"
    command: sh -c "yarn start"
    stdin_open: true
    networks:                                  # 20220825追加
      - postgres-test-network                  # 20220825追加

#---k_212api_dev-+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+----#
  212api_dev:
    build: ../k_902set_dev/212set_dev
    tty: true
    volumes:
      - ../k_212api_dev:/go/src/work           # 修正
    networks:                                  # 20220825追加
      - postgres-test-network                  # 20220825追加

#---k_311dbs_dev-+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+----#
  312dbs_dev:
    image: postgres:14
  # container_name: k_311dbs_pg_g # 変更：postgres -> k_311dbs_pg_g
    command: -c 'config_file=/etc/postgresql/postgresql.conf' # 追加
    ports:
      - 5432:5432
    volumes: # 永続データはどこにおいてどう記述する？
      - db-store:/var/lib/postgresql/data
      - ./311set_dev/initdb:/docker-entrypoint-initdb.d #sql指定 initdb
      - ./311set_dev/config/postgresql.conf:/etc/postgresql/postgresql.conf
    environment:
      - POSTGRES_PASSWORD=${PGSQL_PW}          # 環境変数->${PGSQL_PW}
    networks:                                  # 20220825追加
      - postgres-test-network                  # 20220825追加

#---k_311dbs_dev-+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+----#
volumes:
  db-store:

##---k_211aps_dev-+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+----#
networks:
  postgres-test-network:                        # 20220825追加
    driver: bridge                              # 20220825追加
#    external:
#      name: postgres-test-network