version: "3"
services:
  node:                    # コンテナ名
    build: .               # Dockerfile のあるディレクトリのパスを指定
    volumes:
      - ./:/usr/src/app
    ports:
      - "3000:3000"
    command: sh -c "cd k_112wbs_re_dev_d && yarn start"
    stdin_open: true
