version: "3"
services:

#---k_313dbs_dev-+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+----#
  313dbs_dev:
    image: postgres:14
  # container_name: 313dbs_dev # 変更：postgres -> 313dbs_dev
    command: -c 'config_file=/etc/postgresql/postgresql.conf'
    ports:
      - 5432:5432
    tty: true # 脱落防止
    volumes:
      - db-store:/var/lib/postgresql/data
      - ./313set_dev/initdb:/docker-entrypoint-initdb.d
      - ./313set_dev/config/postgresql.conf:/etc/postgresql/postgresql.conf
    environment:
      - POSTGRES_PASSWORD=${PGSQL_PW}          # 環境変数->${PGSQL_PW}

#---k_313dbs_dev-+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+----#
volumes:
  db-store:
