FROM postgres:14-alpine
ENV LANG ja_JP.utf8

# RUN ["apt-get", "update"]
# RUN ["apt-get", "install", "-y", "cron"]

# COPY pg_dump.sh /usr/local/bin
# COPY pg_restore.sh /usr/local/bin

# CMD ["cron", "-f"]