// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package sqlc_pkg

import (
	"database/sql"
	"time"
)

type AccountAttribute struct {
	AccountID         string         `json:"account_id"`
	SelfIntroduction  sql.NullString `json:"self_introduction"`
	TwitterUri        sql.NullString `json:"twitter_uri"`
	FacebookUri       sql.NullString `json:"facebook_uri"`
	InstagramUri      sql.NullString `json:"instagram_uri"`
	YoutubeChannelUri sql.NullString `json:"youtube_channel_uri"`
	Skill             string         `json:"skill"`
	Rate              sql.NullString `json:"rate"`
	Status            sql.NullString `json:"status"`
	CreateDate        time.Time      `json:"create_date"`
	UpdateDate        time.Time      `json:"update_date"`
}

type AccountMaster struct {
	AccountID        string    `json:"account_id"`
	AccountName      string    `json:"account_name"`
	MailAddless      string    `json:"mail_addless"`
	Password         string    `json:"password"`
	ZipCode          string    `json:"zip_code"`
	BarthDate        time.Time `json:"barth_date"`
	TimeZone         string    `json:"time_zone"`
	Language         string    `json:"language"`
	RegistrationDate time.Time `json:"registration_date"`
	CreateDate       time.Time `json:"create_date"`
	UpdateDate       time.Time `json:"update_date"`
}

type OfferList struct {
	OfferID       string         `json:"offer_id"`
	AccountID     string         `json:"account_id"`
	OfferType     string         `json:"offer_type"`
	OfferTitle    string         `json:"offer_title"`
	OfferSeverity sql.NullString `json:"offer_severity"`
	OfferCatagory sql.NullString `json:"offer_catagory"`
	OfferLocation sql.NullString `json:"offer_location"`
	OfferStatus   string         `json:"offer_status"`
	OfferText     string         `json:"offer_text"`
	CreateDate    time.Time      `json:"create_date"`
	UpdateDate    time.Time      `json:"update_date"`
}

type PurchaseHistroy struct {
	PurchaseID     string    `json:"purchase_id"`
	PurchaseDate   string    `json:"purchase_date"`
	PurchaseTime   string    `json:"purchase_time"`
	PayerAccountID string    `json:"payer_account_id"`
	PayeeAccountID string    `json:"payee_account_id"`
	Amount         string    `json:"amount"`
	CreateDate     time.Time `json:"create_date"`
	UpdateDate     time.Time `json:"update_date"`
}
